name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node-version }}

      - name: run CI
        run: |
          yarn install
          yarn lint
          yarn test
          yarn build
